### ISSUE TITLE
reading 'length'

### ISSUE THREAD

**Issue by cebar2002** [JoshnaksPNG/Bad_Apple_Youtube_Page#3]
``TypeError: Cannot read properties of null (reading 'length')
    at resized_frames (C:\git\Bad_Apple_Youtube_Page\index.js:52:30)
    at C:\git\Bad_Apple_Youtube_Page\node_modules\ffmpeg\lib\video.js:583:5
    at C:\git\Bad_Apple_Youtube_Page\node_modules\ffmpeg\lib\utils.js:20:3
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)``

**Comment by Rudxain** [comment]
That's weird. What did you do exactly? Please post reproduction-steps.

Remember to follow the instructions in the README.md. Make sure the terminal's working-directory is the project folder, not the home directory, not desktop, not system32

**Comment by Specifix5** [comment]
>` (C:\git\Bad_Apple_Youtube_Page\index.js:52:30)`
Seems that you haven't fixed the directory from the config file.
And if the problem still persist after doing that, check your FFmpeg
type "ffmpeg" into cmd and if it's not recognized, watch a yt tutorial on how to properly install it.

**Comment by mrbarsikved** [comment]
a similar problem. ffmpeg is installed. 
![image](https://github.com/JoshnaksPNG/Bad_Apple_Youtube_Page/assets/155853552/81464964-38fe-4b57-af4f-32bb4a6b7cea)
how fix?
